version: "3"
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    depends_on: 
      - postgres
    volumes:
      - ./:/api
      - ./scripts:/scripts
      - ./tests:/api/tests
    networks:
      - api-unico

  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: unico
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-unico:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - api-unico

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-unico:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - api-unico

networks: 
  api-unico:
    driver: bridge

volumes:
  pgadmin-unico:
  db-unico: