definitions:
  domain.FreeMarket:
    properties:
      address:
        type: string
      addressNumber:
        type: string
      areaP:
        type: string
      district:
        type: string
      id:
        type: integer
      latitude:
        type: number
      longitude:
        type: number
      marketName:
        type: string
      reference:
        type: string
      region:
        type: string
      regionCode:
        type: integer
      regionEight:
        type: string
      regionFive:
        type: string
      register:
        type: string
      setCens:
        type: string
      subprefecture:
        type: string
      subprefectureCode:
        type: integer
    type: object
  dto.FreeMarketRequestBody:
    properties:
      address:
        example: RUA MARAGOJIPE
        maxLength: 34
        type: string
      addressNumber:
        example: S/N
        maxLength: 5
        type: string
      areaP:
        example: "3550308005040"
        maxLength: 13
        type: string
      district:
        example: VL FORMOSA
        maxLength: 20
        type: string
      latitude:
        example: -28.460924
        type: number
      longitude:
        example: -52.210348
        type: number
      marketName:
        example: VILA FORMOSA
        maxLength: 30
        type: string
      reference:
        example: TV RUA PRETORIA
        maxLength: 34
        type: string
      region:
        example: VILA FORMOSA
        maxLength: 18
        type: string
      regionCode:
        example: 87
        type: integer
      regionEight:
        example: Leste 1
        maxLength: 7
        type: string
      regionFive:
        example: Leste
        maxLength: 6
        type: string
      register:
        example: 4041-0
        maxLength: 6
        type: string
      setCens:
        example: "355030885000091"
        maxLength: 15
        type: string
      subprefecture:
        example: ARICANDUVA-FORMOSA-CARRAO
        maxLength: 25
        type: string
      subprefectureCode:
        example: 26
        type: integer
    required:
    - address
    - areaP
    - district
    - latitude
    - longitude
    - marketName
    - region
    - regionCode
    - regionEight
    - regionFive
    - register
    - setCens
    - subprefecture
    - subprefectureCode
    type: object
  dto.PaginationResponseBody:
    properties:
      items: {}
      total:
        type: integer
    type: object
  util.Field:
    properties:
      field:
        type: string
      message:
        type: string
    type: object
  util.RequestError:
    properties:
      fields:
        items:
          $ref: '#/definitions/util.Field'
        type: array
    type: object
info:
  contact: {}
paths:
  /free-market:
    get:
      consumes:
      - application/json
      description: Fetch free markets with server pagination
      parameters:
      - description: column_name1,column_name2
        in: query
        name: sort
        type: string
      - description: true,false
        in: query
        name: descending
        type: string
      - description: "1"
        in: query
        name: page
        required: true
        type: integer
      - description: "10"
        in: query
        name: itemsPerPage
        required: true
        type: integer
      - description: string word, can be empty
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.PaginationResponseBody'
      summary: Fetch free markets with server pagination
      tags:
      - free-market
    post:
      consumes:
      - application/json
      description: Create free market
      parameters:
      - description: freeMarket
        in: body
        name: freeMarket
        required: true
        schema:
          $ref: '#/definitions/dto.FreeMarketRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.FreeMarket'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/util.RequestError'
      summary: Create free market
      tags:
      - free-market
  /free-market/{id}:
    delete:
      consumes:
      - application/json
      description: Delete free market by id
      parameters:
      - description: "1"
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.FreeMarket'
      summary: Delete free market by id
      tags:
      - free-market
    get:
      consumes:
      - application/json
      description: Get free market by id
      parameters:
      - description: "1"
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.FreeMarket'
      summary: Get free market by id
      tags:
      - free-market
    put:
      consumes:
      - application/json
      description: Update free market by id
      parameters:
      - description: freeMarket
        in: body
        name: freeMarket
        required: true
        schema:
          $ref: '#/definitions/dto.FreeMarketRequestBody'
      - description: "1"
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.FreeMarket'
      summary: Update free market by id
      tags:
      - free-market
swagger: "2.0"
